# Generated by Django 3.2.12 on 2022-05-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
