# Generated by Django 3.2.12 on 2022-05-20 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
